FROM ubuntu/apache2
LABEL authors="barber"

RUN apt update && apt install -y libapache2-mod-auth-openidc ca-certificates && a2enmod auth_openidc proxy proxy_http proxy_wstunnel rewrite headers ssl && \
    sed -i 's/Listen 80/Listen 8080/' /etc/apache2/ports.conf


CMD ["/bin/bash", "-c", "apache2-foreground"]
